version: '3.8'

services:
 # Service pour le backend Spring Boot
  backend:
    build:  #Indique que l'image Docker sera construite à partir du Dockerfile présent dans le répertoire courant.
      context: ./tp4jenkins
    ports:
      - "8082:8082"   # Redirige le port 8082 du conteneur vers le port 8082 de votre machine

      
# Service pour le frontend Angular
  frontend:
    build:
      context: ./angular-app   # Chemin vers le répertoire de votre frontend Angular
    ports:
      - "80:80"   # Le frontend sera accessible sur le port 80 de votre machine
    depends_on:
      - backend    # Assurez-vous que le frontend dépend du backend, si nécessaire

    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/etudiant # URL de connexion à PostgreSQL
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 0000
    depends_on:
      - db

  db:
    image: postgres:latest # Spécifier la version de PostgreSQL ici
    environment:
      POSTGRES_DB: etudiant # Nom de la base de données à créer
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 0000
    ports:
      - "5432:5432" # Expose le port 5432 de PostgreSQL sur l'hôte
